#!/bin/bash
java -cp "`yarn classpath`:target/${project.name}-${project.version}.jar:/Users/mharis/.m2/repository/org/scala-lang/scala-library/${scala.minor}/scala-library-${scala.minor}.jar" "$1" "$2"
